vich_uploader:
    db_driver: orm
    mappings:
        photos:
            uri_prefix: '/image'
            upload_destination: '%kernel.project_dir%/public/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
