vich_uploader:
    db_driver: orm
    mappings:
        photos:
            uri_prefix: '/image/produits'
            upload_destination: '%kernel.project_dir%/public/images/produits'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
