controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

product_search:
    path: /search
    controller: App\Controller\ProductController::search