# Nom de notre workflow
name: Déploiement Prod

# Déclencheur du workflow
on:
  push:
    branches: [Prod]  # Le workflow est déclenché lors d'un push sur la branche "main".
  
# Jobs à exécuter
jobs:
  deploy:
    # Spécifie l'environnement de runner que le job va utiliser
    runs-on: ubuntu-latest

    # Variables d'environnement utilisées dans les étapes suivantes
    env:
      SSHPASS: ${{ secrets.SSH_PASSWORD }}  # Mot de passe SSH pour l'authentification
 
    # Les étapes à exécuter dans ce job
    steps:
      # Première étape : Check-out du code de notre dépôt GitHub
      - uses: actions/checkout@v3

      # Deuxième étape : Installation de sshpass et configuration SSH
      - name: Configuration SSH pour déploiement
        run: |
          sudo apt update && sudo apt install -y sshpass  

      # Troisième étape : Déploiement et configuration sur le serveur distant
      - name: Déploiement et configuration sur le serveur
        run: |
          sshpass -e ssh -T -o StrictHostKeyChecking=no -p 2222 ${{ secrets.REMOTE_USER_BACK }}@${{ secrets.REMOTE_HOST_NAME }} << 'ENDSSH'
            # Naviguer dans le dossier de déploiement
            cd /home/preprodgreenshop/public_html

            git reset --hard
            
            # Vérifier que la branche courante est 'Prod'
            CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            if [ "$CURRENT_BRANCH" != "Prod" ]; then
              echo "Attention : Vous n'êtes pas sur la branche 'Prod'. Opération annulée."
              exit 1
            fi
            
            # Tentative de git pull, si échec alors git clone
            git fetch origin Prod
            git rebase origin/Prod
            
            # Installation et mise à jour des dépendances avec Composer
            composer install
            php bin/console cache:clear
            npm i

            service nginx restart 
            # Copier le contenu de 'servers' dans 'public' avec rsync
            rsync -av servers/ public/

            # Définit les variables d'environnement pour la production et désactive le mode débogage, puis vide le cache pour s'assurer que les modifications sont appliquées
            APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
          ENDSSH
